dirN  = {...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse1/mouse1_180412';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse1/mouse1_180414';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse1/mouse1_180415';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse1/mouse1_180501a';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse1/mouse1_180501b';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse1/mouse1_180502a';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse1/mouse1_180502b';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse3/mouse3_180627';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse3/mouse3_180628';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse3/mouse3_180629';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse4/mouse4_181114b';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse5/mouse5_181112b';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse5/mouse5_181116';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse6/mouse6_190330';...
'/mnt/NyuShare/Buzsakilabspace/LabShare/EnglishD/AxoAxo/mouse6/mouse6_190331';...

};

for i = 1:length(dirN)
optmod{i} = getOptoStim(dirN{i},false);

GetCellParams(dirN{i})


end

%%
